# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{magic_userstamp}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["akimatter"]
  s.date = %q{2009-10-28}
  s.description = %q{This Rails plugin extends ActiveRecord::Base to add automatic updating of created_by and updated_by attributes of your models in much the same way that the ActiveRecord::Timestamp module updates created_(at/on) and updated_(at/on) attributes.}
  s.email = %q{akm2000@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.original",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "LICENSE",
     "README.original",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/userstamp.rb",
     "lib/userstamp/config.rb",
     "lib/userstamp/controller.rb",
     "lib/userstamp/event.rb",
     "lib/userstamp/magic_columns.rb",
     "lib/userstamp/migration_helper.rb",
     "lib/userstamp/stampable.rb",
     "lib/userstamp/stamper.rb",
     "magic_userstamp.gemspec",
     "rdoc/classes/Ddb/Controller.html",
     "rdoc/classes/Ddb/Controller/Userstamp.html",
     "rdoc/classes/Ddb/Controller/Userstamp/InstanceMethods.html",
     "rdoc/classes/Ddb/Userstamp.html",
     "rdoc/classes/Ddb/Userstamp/MigrationHelper.html",
     "rdoc/classes/Ddb/Userstamp/MigrationHelper/InstanceMethods.html",
     "rdoc/classes/Ddb/Userstamp/Stampable.html",
     "rdoc/classes/Ddb/Userstamp/Stampable/ClassMethods.html",
     "rdoc/classes/Ddb/Userstamp/Stamper.html",
     "rdoc/classes/Ddb/Userstamp/Stamper/ClassMethods.html",
     "rdoc/classes/Ddb/Userstamp/Stamper/InstanceMethods.html",
     "rdoc/created.rid",
     "rdoc/files/CHANGELOG.html",
     "rdoc/files/LICENSE.html",
     "rdoc/files/README.html",
     "rdoc/files/lib/migration_helper_rb.html",
     "rdoc/files/lib/stampable_rb.html",
     "rdoc/files/lib/stamper_rb.html",
     "rdoc/files/lib/userstamp_rb.html",
     "rdoc/fr_class_index.html",
     "rdoc/fr_file_index.html",
     "rdoc/fr_method_index.html",
     "rdoc/index.html",
     "rdoc/rdoc-style.css",
     "spec/compatibility_stamping_spec.rb",
     "spec/config_spec.rb",
     "spec/database.yml",
     "spec/fixtures/comments.yml",
     "spec/fixtures/people.yml",
     "spec/fixtures/posts.yml",
     "spec/fixtures/users.yml",
     "spec/magic_column_spec.rb",
     "spec/posts_controller_spec.rb",
     "spec/resources/controllers/application_controller.rb",
     "spec/resources/controllers/posts_controller.rb",
     "spec/resources/controllers/users_controller.rb",
     "spec/resources/controllers/userstamp_controller.rb",
     "spec/resources/models/comment.rb",
     "spec/resources/models/person.rb",
     "spec/resources/models/ping.rb",
     "spec/resources/models/post.rb",
     "spec/resources/models/user.rb",
     "spec/schema.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/stamping_spec.rb",
     "spec/users_controller_spec.rb"
  ]
  s.homepage = %q{http://github.com/akm/magic_userstamp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{creator_id/updater_id/deleter_id support with setting outside models}
  s.test_files = [
    "spec/compatibility_stamping_spec.rb",
     "spec/config_spec.rb",
     "spec/magic_column_spec.rb",
     "spec/posts_controller_spec.rb",
     "spec/resources/controllers/application_controller.rb",
     "spec/resources/controllers/posts_controller.rb",
     "spec/resources/controllers/users_controller.rb",
     "spec/resources/controllers/userstamp_controller.rb",
     "spec/resources/models/comment.rb",
     "spec/resources/models/person.rb",
     "spec/resources/models/ping.rb",
     "spec/resources/models/post.rb",
     "spec/resources/models/user.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb",
     "spec/stamping_spec.rb",
     "spec/users_controller_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

